site_name: YDMS Composite Actions Templates

repo_name: Yellow-Dog-Man/composite-actions-templates
repo_url: https://github.com/Yellow-Dog-Man/composite-actions-templates

site_url: 'https://yellow-dog-man.github.io/composite-actions-templates/'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Composite Actions:
      - Unity Download: composite/unity-download.md
      - CMake Build: composite/cmake-build.md
      - Docker Build Push: composite/docker-build-push.md
      - .NET Build: composite/dotnet-build.md
      - .NET Build Push: composite/dotnet-build-push-nuget.md
      - .NET Run Tests: composite/dotnet-tests-run.md
      - Upload to R2: composite/upload-to-r2.md
      - Download from R2: composite/download-from-r2.md
  - Reusable Workflows:
      - Secret Detection: workflows/secret-detection.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: github
      handlers:
        github:
          options:
            signature_show_permissions: true
            signature_version: string
            signature_version_string: !!python/object/apply:os.getenv ["GITHUB_REF_NAME", "main"]
            show_toc_entry: false
            heading_level: 3
            parameters_anchors: false
            parameters_groups: false
            parameters_group_title_row: true
            show_source: true
            show_outputs: true
            show_secrets: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Yellow-Dog-Man/
  version:
    provider: mike
    default: main
